version: "3"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    image: odoo:16
    depends_on:
      - db
    volumes:
      - odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    ports:
      - "80:8069"
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=${PASSWORD}

volumes:
    db:
        driver: local
    odoo:
        driver: local